/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 67e72bdcecdccf1474b04f87e3531d60)
interface __BaseEnv_CloudflareBindings {
	ARTWORK: R2Bucket;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	SITE_URL: string;
	OUTBID_EMAIL_FROM: string;
	CUSTOM_WRAP_EMAIL_TEST_TO?: string;
	STRIPE_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	AUCTION: DurableObjectNamespace<import("./worker/index").Auction>;
	CUSTOM_WRAP_EMAIL_TO?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "Auction";
	}
	interface StagingEnv {
		ARTWORK: R2Bucket;
		EMAIL: SendEmail;
		ASSETS: Fetcher;
		SITE_URL: string;
		OUTBID_EMAIL_FROM: string;
		CUSTOM_WRAP_EMAIL_TEST_TO: string;
		STRIPE_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		AUCTION: DurableObjectNamespace<import("./worker/index").Auction>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "OUTBID_EMAIL_FROM" | "CUSTOM_WRAP_EMAIL_TEST_TO" | "STRIPE_API_KEY" | "STRIPE_WEBHOOK_SECRET" | "CUSTOM_WRAP_EMAIL_TO">> {}
}
