/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: e64e1cf2b016e7e4dc19654c47fddd4c)
interface __BaseEnv_CloudflareBindings {
	ARTWORK: R2Bucket;
	ASSETS: Fetcher;
	SITE_URL: string;
	STRIPE_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	AUCTION: DurableObjectNamespace<import("./worker/index").Auction>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "Auction";
	}
	interface StagingEnv {
		ARTWORK: R2Bucket;
		ASSETS: Fetcher;
		SITE_URL: string;
		STRIPE_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		AUCTION: DurableObjectNamespace<import("./worker/index").Auction>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "STRIPE_API_KEY" | "STRIPE_WEBHOOK_SECRET">> {}
}
